pub mod core;
pub mod graphics;
pub mod input;
pub mod audio;
pub mod math;
pub mod assets;
pub mod scene;
pub mod animation;
pub mod physics;
pub mod physics3d;
pub mod ui;
pub mod game_builder;
pub mod gameplay;
pub mod error;
pub mod logging;
pub mod diagnostics;
pub mod save_system;
pub mod prelude;
pub mod generation;
pub mod gpu;
pub mod rendering;
pub mod platform;
pub mod ai;
pub mod ai_game;
pub mod ai_systems;
pub mod character;
pub mod immersive;
pub mod multiplayer;
pub mod npc;
pub mod performance;
pub mod scripting;
pub mod spatial;
pub mod story;
pub mod tools;
pub mod vehicle;
pub mod world;
pub mod build_mode; // Re-enabled to check compilation errors
pub mod community;
pub mod collaboration;
pub mod networking;

pub use core::Engine;
pub use game_builder::GameBuilder;
pub use physics::{PhysicsWorld, RigidBody, Collider, ColliderShape};
pub use physics3d::{PhysicsWorld3D, PhysicsHandle, BodyType3D, ColliderShape3D, BodyDescriptor, CollisionEvent3D, Physics3DConfig};