[package]
name = "robin_3d_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.20"
winit = "0.29"
env_logger = "0.10"
pollster = "0.3"
cgmath = "0.18"
bytemuck = { version = "1.4", features = ["derive"] }

[[bin]]
name = "robin_3d_demo"
path = "src/main.rs"